#!/usr/bin/env bash

PD_DISAGG_MOUNT="${PD_DISAGG_MOUNT:-/mnt/pd-disagg}"
VIRTUAL_ENV="${VIRTUAL_ENV:-${PD_DISAGG_MOUNT}/venvs/vllm-tpu}"
HF_HOME="${HF_HOME:-${PD_DISAGG_MOUNT}/cache/huggingface}"
HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-${HF_HOME}/hub}"
MODEL_ID="${MODEL_ID:-Qwen/Qwen3-4B}"
MODEL_REVISION="${MODEL_REVISION:-1cfa9a7208912126459214e8b04321603b3df60c}"
TENSOR_PARALLEL_SIZE="${TENSOR_PARALLEL_SIZE:-4}"
PATH="${VIRTUAL_ENV}/bin:${PD_DISAGG_MOUNT}/bin:${PATH}"

export PD_DISAGG_MOUNT VIRTUAL_ENV HF_HOME HUGGINGFACE_HUB_CACHE
export MODEL_ID MODEL_REVISION TENSOR_PARALLEL_SIZE PATH
