#!/usr/bin/env bash

# Non-secret, overridable Phase 0 defaults.
PROJECT_ID="${PROJECT_ID:-disagg-503619}"
REGION="${REGION:-us-central1}"
ZONE="${ZONE:-us-central1-a}"

TPU_NAME="${TPU_NAME:-pd-phase0-v5e-4}"
QUEUED_RESOURCE_ID="${QUEUED_RESOURCE_ID:-pd-phase0-v5e-4-q}"
ACCELERATOR_TYPE="${ACCELERATOR_TYPE:-v5litepod-4}"
RUNTIME_VERSION="${RUNTIME_VERSION:-v2-alpha-tpuv5-lite}"
TPU_PROVISIONING_MODEL="${TPU_PROVISIONING_MODEL:-spot}"

DATA_DISK_NAME="${DATA_DISK_NAME:-pd-phase0-data}"
DATA_DISK_SIZE="${DATA_DISK_SIZE:-200GB}"
DATA_DISK_TYPE="${DATA_DISK_TYPE:-pd-balanced}"

NETWORK="${NETWORK:-default}"
MODEL_ID="${MODEL_ID:-Qwen/Qwen3-4B}"

export PROJECT_ID REGION ZONE
export TPU_NAME QUEUED_RESOURCE_ID ACCELERATOR_TYPE RUNTIME_VERSION
export TPU_PROVISIONING_MODEL
export DATA_DISK_NAME DATA_DISK_SIZE DATA_DISK_TYPE NETWORK MODEL_ID
